#!/usr/bin/env python3
"""Freeze independent SQL reference results and evaluate historical semantics offline.

The snapshot must first be captured with BigQuerySemanticSource. Expected results
are authored as SQLite SQL over that frozen input, never generated by run_query.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import sqlite3
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.agent.semantic_source import load_snapshot  # noqa: E402
from app.agent.semantics import (  # noqa: E402
    CATALOG_PATH,
    Query,
    compare_queries,
    load_contract,
    resolve_entity,
    run_query,
)

# Explicit independent reference expressions. Do not derive from the YAML contract.
FORMULAS = {
    "pts": "SUM(pts)*1.0/COUNT(*)",
    "fg_pct": "SUM(fgm)*1.0/NULLIF(SUM(fga),0)",
    "ts_pct": "SUM(pts)*1.0/NULLIF(2*(SUM(fga)+0.44*SUM(fta)),0)",
}


def database(rows: list[dict[str, Any]]) -> sqlite3.Connection:
    conn = sqlite3.connect(":memory:")
    conn.row_factory = sqlite3.Row
    columns = list(rows[0])
    # Identifiers are fixed by the capture adapter; validate before SQL interpolation.
    allowed = set(
        "season season_type game_id player_id player_name game_date team_abbr opponent_abbr pts reb ast stl blk tov fg3m min fgm fga ftm fta fg3a plus_minus".split()
    )
    if set(columns) != allowed:
        raise ValueError("Unexpected snapshot columns")
    conn.execute("CREATE TABLE games (" + ", ".join(columns) + ")")
    conn.executemany(
        "INSERT INTO games VALUES (" + ",".join("?" for _ in columns) + ")",
        [tuple(row[c] for c in columns) for row in rows],
    )
    return conn


def reference_sql(metric: str, *, ranked: bool = False, recent: bool = False) -> str:
    selected = (
        "SELECT * FROM games WHERE season=:season AND season_type=:phase "
        "AND game_date<=:as_of AND (:team IS NULL OR team_abbr=:team) "
    )
    if not ranked:
        selected += "AND player_id=:player "
    selected += "ORDER BY game_date DESC, game_id DESC "
    if recent:
        selected += "LIMIT :n OFFSET :offset"
    component_check = {
        "pts": "pts IS NOT NULL",
        "fg_pct": "fgm IS NOT NULL AND fga IS NOT NULL",
        "ts_pct": "pts IS NOT NULL AND fga IS NOT NULL AND fta IS NOT NULL",
    }[metric]
    numerator, denominator = {
        "pts": ("SUM(pts)", "COUNT(*)"),
        "fg_pct": ("SUM(fgm)", "SUM(fga)"),
        "ts_pct": ("SUM(pts)", "2*(SUM(fga)+0.44*SUM(fta))"),
    }[metric]
    grouped = (
        f"SELECT player_id, COUNT(*) AS games, {FORMULAS[metric]} AS value, "
        f"{numerator} AS numerator, {denominator} AS denominator, "
        "SUM(fga) AS attempts, GROUP_CONCAT(game_id, ',') AS game_ids "
        f"FROM selected WHERE {component_check} GROUP BY player_id"
    )
    if ranked:
        # Complete-component samples only. Count source independently of valid rows.
        grouped += (
            " HAVING COUNT(*)>=:min_games AND SUM(fga)>=:min_attempts "
            "AND COUNT(*)=(SELECT COUNT(*) FROM selected s WHERE s.player_id=selected.player_id)"
        )
    sql = f"WITH selected AS ({selected}), aggregated AS ({grouped}) "
    return sql + (
        "SELECT *, COUNT(*) OVER() AS cohort_size, RANK() OVER(ORDER BY value DESC) AS rank FROM aggregated WHERE value IS NOT NULL ORDER BY rank, player_id LIMIT 100"
        if ranked
        else "SELECT * FROM aggregated ORDER BY player_id"
    )


def freeze_references(snapshot_path: Path) -> dict[str, Any]:
    snapshot, _ = load_snapshot(snapshot_path)
    conn = database(snapshot["rows"])
    cases = []
    for season in sorted({r["season"] for r in snapshot["rows"]}):
        # Independent SQL selects reproducible examples, with no player-name guessing.
        player = conn.execute(
            "SELECT player_id FROM games WHERE season=? GROUP BY player_id "
            "HAVING COUNT(DISTINCT season_type)=2 ORDER BY COUNT(*) DESC, player_id LIMIT 1",
            (season,),
        ).fetchone()[0]
        trade = conn.execute(
            "SELECT player_id, MIN(team_abbr) AS team FROM games WHERE season=? AND season_type='Regular Season' "
            "GROUP BY player_id HAVING COUNT(DISTINCT team_abbr)>1 ORDER BY player_id LIMIT 1",
            (season,),
        ).fetchone()
        identity = conn.execute(
            "SELECT player_id, MIN(player_name) AS player_name FROM games WHERE season=? "
            "GROUP BY player_id HAVING COUNT(*)<5 ORDER BY player_id LIMIT 1",
            (season,),
        ).fetchone()
        cases.append(
            {
                "id": f"{season}/identity",
                "family": "identity",
                "kind": "identity",
                "name": identity["player_name"],
                "expected": identity["player_id"],
            }
        )
        for name, metric, phase, window in (
            ("regular_ppg", "pts", "Regular Season", None),
            ("playoff_ppg", "pts", "Playoffs", None),
            ("fg_ratio", "fg_pct", "Regular Season", None),
            ("ts_ratio", "ts_pct", "Regular Season", None),
            ("trade", "pts", "Regular Season", None),
            ("last_five", "pts", "Regular Season", "last_n_games"),
            ("prior_five", "pts", "Regular Season", "prior_n_games"),
            ("ts_leaders", "ts_pct", "Regular Season", None),
        ):
            anchor = conn.execute(
                "SELECT MAX(game_date) FROM games WHERE season=? AND season_type=?",
                (season, phase),
            ).fetchone()[0]
            ranked = name == "ts_leaders"
            selected_player = trade["player_id"] if name == "trade" else player
            params = {
                "season": season,
                "phase": phase,
                "as_of": anchor,
                "team": trade["team"] if name == "trade" else None,
                "player": selected_player,
                "n": 5,
                "offset": 5 if window == "prior_n_games" else 0,
                "min_games": 5,
                "min_attempts": 200,
            }
            query = {
                "metric": metric,
                "season": season,
                "season_type": phase,
                "aggregation": "average" if metric == "pts" else "ratio",
                "as_of": anchor,
                "player_id": None if ranked else selected_player,
                "team_abbr": params["team"],
                "operation": "rank" if ranked else "summary",
                "limit": 100,
            }
            if window:
                query.update(window=window, n=5)
            if ranked:
                query.update(min_games=5, min_attempts=200)
            sql = reference_sql(metric, ranked=ranked, recent=bool(window))
            expected = [dict(r) for r in conn.execute(sql, params)]
            for row in expected:
                row["game_ids"] = sorted(row["game_ids"].split(","))
            family = (
                "trade"
                if name == "trade"
                else "comparison"
                if window
                else "cohort"
                if ranked
                else "phase"
                if metric == "pts"
                else "ratio"
            )
            cases.append(
                {
                    "id": f"{season}/{name}",
                    "family": family,
                    "kind": "query",
                    "query": query,
                    "reference_sql": sql,
                    "parameters": params,
                    "expected": expected,
                }
            )
    conn.close()
    return {
        "version": 1,
        "snapshot_sha256": snapshot["sha256"],
        "contract_sha256": hashlib.sha256(CATALOG_PATH.read_bytes()).hexdigest(),
        "human_reviewed": False,
        "review_date": None,
        "cases": cases,
    }


def evaluate(snapshot_path: Path, reference_path: Path) -> dict[str, Any]:
    snapshot, evidence = load_snapshot(snapshot_path)
    reference_bytes = reference_path.read_bytes()
    reference = json.loads(reference_bytes)
    if reference["snapshot_sha256"] != snapshot["sha256"]:
        raise ValueError("Reference belongs to another source snapshot")
    if (
        reference["contract_sha256"]
        != hashlib.sha256(CATALOG_PATH.read_bytes()).hexdigest()
    ):
        raise ValueError("Contract changed; reference review required")
    players = list(
        {
            (r["player_id"], r["player_name"]): {
                "player_id": r["player_id"],
                "player_name": r["player_name"],
            }
            for r in snapshot["rows"]
        }.values()
    )
    results = []
    query_results = {}
    for case in reference["cases"]:
        errors = []
        if case["kind"] == "identity":
            actual = resolve_entity(case["name"], players)
            if (
                actual["status"] != "ok"
                or actual["matches"][0]["player_id"] != case["expected"]
            ):
                errors.append("entity")
        else:
            actual = run_query(evidence, Query(**case["query"]))
            query_results[case["id"]] = actual
            expected = case["expected"]
            if [r["player_id"] for r in actual["rows"]] != [
                r["player_id"] for r in expected
            ]:
                errors.append("cohort")
            for a, e in zip(actual["rows"], expected):
                if not (a["value"] is None and e["value"] is None) and not (
                    a["value"] is not None
                    and e["value"] is not None
                    and math.isclose(a["value"], e["value"], rel_tol=0, abs_tol=1e-6)
                ):
                    errors.append("metric_math")
                if (
                    a["observed_games"] != e["games"]
                    or sorted(a["game_ids"]) != e["game_ids"]
                ):
                    errors.append("sample")
                for field in ("numerator", "denominator"):
                    if not math.isclose(a[field], e[field], rel_tol=0, abs_tol=1e-6):
                        errors.append("components")
                if "cohort_size" in e and actual["cohort"]["size"] != e["cohort_size"]:
                    errors.append("cohort")
                if "rank" in e and a["rank"] != e["rank"]:
                    errors.append("rank")
            if (
                actual["scope"]["as_of"] != case["parameters"]["as_of"]
                or not actual["provenance"]["snapshot_id"]
            ):
                errors.append("evidence")
        results.append(
            {
                "id": case["id"],
                "family": case["family"],
                "passed": not errors,
                "failure_categories": sorted(set(errors)),
            }
        )
    # Verify actual comparison output against separately frozen period references.
    for season in sorted({r["season"] for r in snapshot["rows"]}):
        recent = next(c for c in reference["cases"] if c["id"] == f"{season}/last_five")
        prior = next(c for c in reference["cases"] if c["id"] == f"{season}/prior_five")
        actual = compare_queries(
            evidence, Query(**recent["query"]), Query(**prior["query"])
        )
        expected_delta = recent["expected"][0]["value"] - prior["expected"][0]["value"]
        passed = (
            math.isclose(actual["difference"], expected_delta, abs_tol=1e-6, rel_tol=0)
            and not actual["overlapping_game_ids"]
        )
        results.append(
            {
                "id": f"{season}/comparison",
                "family": "comparison",
                "passed": passed,
                "failure_categories": [] if passed else ["comparison"],
            }
        )
    return {
        "contract_version": load_contract().version,
        "evidence_kind": "historical",
        "snapshot_sha256": snapshot["sha256"],
        "reference_sha256": hashlib.sha256(reference_bytes).hexdigest(),
        "human_reviewed": reference["human_reviewed"],
        "passed": sum(r["passed"] for r in results),
        "total": len(results),
        "llm_runs": 0,
        "capture": snapshot["capture"],
        "missing_families": ["injury"],
        "release_ready": False,
        "limitations": [
            "Independent historical SQL checks; no natural-language agent calls.",
            "Human reference review and historical injury case remain required.",
        ],
        "results": results,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--snapshot", type=Path, required=True)
    parser.add_argument("--references", type=Path, required=True)
    parser.add_argument(
        "--freeze",
        action="store_true",
        help="Create references once; never overwrite reviewed expectations",
    )
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    if args.freeze:
        references = freeze_references(args.snapshot)
        args.references.parent.mkdir(parents=True, exist_ok=True)
        with args.references.open("x") as stream:
            stream.write(json.dumps(references, indent=2) + "\n")
    report = evaluate(args.snapshot, args.references)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, indent=2) + "\n")
    print(
        json.dumps(
            {k: v for k, v in report.items() if k not in ("results", "capture")},
            indent=2,
        )
    )
    return 0 if report["passed"] == report["total"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
